// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrnekCoreWebApi.Models;

namespace OrnekCoreWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231019111942_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OrnekCoreWebApi.Models.Ilce", b =>
                {
                    b.Property<int>("IlceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IlceAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IlceBaskan")
                        .HasColumnType("int");

                    b.Property<int>("SehirID")
                        .HasColumnType("int");

                    b.HasKey("IlceID");

                    b.HasIndex("SehirID");

                    b.ToTable("Ilces");
                });

            modelBuilder.Entity("OrnekCoreWebApi.Models.Sehir", b =>
                {
                    b.Property<int>("SehirID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SehirAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SehirIlceSay")
                        .HasColumnType("int");

                    b.Property<int>("UlkeID")
                        .HasColumnType("int");

                    b.HasKey("SehirID");

                    b.HasIndex("UlkeID");

                    b.ToTable("Sehirs");
                });

            modelBuilder.Entity("OrnekCoreWebApi.Models.Ulke", b =>
                {
                    b.Property<int>("UlkeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UlkeAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UlkeBaskent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UlkeSehirSay")
                        .HasColumnType("int");

                    b.HasKey("UlkeID");

                    b.ToTable("Ulkes");
                });

            modelBuilder.Entity("OrnekCoreWebApi.Models.Ilce", b =>
                {
                    b.HasOne("OrnekCoreWebApi.Models.Sehir", "Sehir")
                        .WithMany()
                        .HasForeignKey("SehirID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sehir");
                });

            modelBuilder.Entity("OrnekCoreWebApi.Models.Sehir", b =>
                {
                    b.HasOne("OrnekCoreWebApi.Models.Ulke", "Ulke")
                        .WithMany()
                        .HasForeignKey("UlkeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ulke");
                });
#pragma warning restore 612, 618
        }
    }
}
